on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install rust toolchain
        run: |
          apt-get update
          apt-get install rustup
