on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          # Add cargo to the global action PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Build
        run: cargo build --release
