on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf -y https://sh.rustup.rs | sh
